version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    volumes:
      - pihole_data:/etc/pihole/
      - ./data/dnsmasq:/etc/dnsmasq.d/
      - ./data/logs:/var/log/pihole/
    environment:
      TZ: "${TIMEZONE}"
      WEBPASSWORD: "${WEBPASSWORD}"
      PIHOLE_DNS_: unbound;9.9.9.9;1.1.1.1;5.11.11.11
      VIRTUAL_HOST: pi.hole
      DNSSEC: true
      DNSMASQ_LISTENING: all
    depends_on:
      - unbound
  unbound:
    restart: always
    image: tiredofit/unbound:latest
volumes:
  pihole_data:
