services:
  pihole:
    image: pihole/pihole:latest
    restart: always
    ports:
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:8053:80/tcp"
    cap_add:
      - SYS_TIME
      - SYS_NICE
    environment:
      TZ: "${TIMEZONE}"
      FTLCONF_webserver_api_password: "${WEBPASSWORD}"
      FTLCONF_dns_upstreams: unbound;5.11.11.5;9.9.9.9;1.1.1.3
      FTLCONF_dns_dnssec: true
      FTLCONF_dns_listeningMode: local
      FTLCONF_misc_dnsmasq_lines: address=/test/127.0.0.1
    depends_on:
      - unbound
  unbound:
    restart: always
    image: tiredofit/unbound:latest
